import {
  airtablePaletteStyle,
  type AirtableColorToken,
} from "@/lib/airtable-choice-colors";

/**
 * Extra dest-column option lists for the case page.
 * Names + tokens copied from
 * https://docs.google.com/document/d/1TXyrXFuQJPQqbm60Z6gdsqzWpFegIQr5XZLeqc5xUGY
 *
 * Hex comes from `AIRTABLE_PALETTE_HEX` (official SDK palette). Do not add
 * a second map. Truncated lists stay truncated. Stored values missing from a
 * list are still shown in the control.
 */

export type SelectOption = {
  name: string;
  color: AirtableColorToken;
};

export type CaseSelectFieldKey = keyof typeof CASE_SELECT_OPTIONS;

export const CASE_SELECT_OPTIONS = {
  claim_state: [
    { name: "AK", color: "cyanBright" },
    { name: "AL", color: "yellowBright" },
    { name: "AR", color: "yellowBright" },
    { name: "AZ", color: "greenBright" },
    { name: "CA", color: "purpleBright" },
    { name: "CO", color: "greenBright" },
    { name: "CT", color: "redBright" },
    { name: "DC", color: "redBright" },
    { name: "DE", color: "redBright" },
    { name: "FL", color: "redBright" },
    { name: "GA", color: "redBright" },
    { name: "HI", color: "cyanBright" },
    { name: "IA", color: "yellowBright" },
    { name: "ID", color: "greenBright" },
    { name: "IL", color: "yellowBright" },
    { name: "IN", color: "redBright" },
    { name: "KS", color: "yellowBright" },
    { name: "KY", color: "redDark1" },
    { name: "LA", color: "yellowBright" },
    { name: "MA", color: "redBright" },
    { name: "MD", color: "redBright" },
    { name: "ME", color: "redBright" },
    { name: "MI", color: "redBright" },
    { name: "MN", color: "yellowBright" },
    { name: "MO", color: "yellowBright" },
    { name: "MS", color: "yellowBright" },
    { name: "MT", color: "greenBright" },
    { name: "NC", color: "redBright" },
    { name: "ND", color: "yellowBright" },
    { name: "NE", color: "yellowBright" },
    { name: "NH", color: "redBright" },
    { name: "NJ", color: "redBright" },
    { name: "NM", color: "greenBright" },
    { name: "NV", color: "purpleBright" },
    { name: "NY", color: "redBright" },
    { name: "OH", color: "redBright" },
    { name: "OK", color: "yellowBright" },
    { name: "OR", color: "purpleBright" },
    { name: "PA", color: "redBright" },
    { name: "RI", color: "redBright" },
    { name: "SC", color: "redBright" },
    { name: "SD", color: "yellowBright" },
    { name: "TN", color: "redDark1" },
    { name: "TX", color: "yellowBright" },
    { name: "UT", color: "greenBright" },
    { name: "VA", color: "redBright" },
    { name: "VT", color: "redBright" },
    { name: "WA", color: "purpleBright" },
    { name: "WI", color: "yellowBright" },
    { name: "WV", color: "redBright" },
  ],
  resolutions_specialist: [
    { name: "A2 - Aidee Gutierrez", color: "blueBright" },
    { name: "A2 - Andrea Robles", color: "greenLight1" },
    { name: "Jetta Lewis", color: "tealLight1" },
    { name: "Tiffany Nicholson", color: "pinkBright" },
    { name: "Not assigned", color: "grayDark1" },
  ],
  paralegal: [
    { name: "Brittany Owens", color: "purpleBright" },
    { name: "Kristie Fogner", color: "blueBright" },
    { name: "Marisol Rivera", color: "tealBright" },
  ],
  department: [
    { name: "Onboarding", color: "blueLight1" },
    { name: "Retained", color: "orangeLight1" },
    { name: "Settled", color: "greenLight1" },
    { name: "Claim Closed", color: "greenLight2" },
  ],
  case_status: [
    { name: "Referral", color: "blueLight1" },
    { name: "Pre-Litigation", color: "pinkLight1" },
    { name: "Appraisal", color: "yellowLight1" },
    { name: "Appraisal - Lit", color: "yellowBright" },
    { name: "Re-Inspection", color: "purpleBright" },
    { name: "Litigation", color: "tealLight1" },
    { name: "Settled", color: "greenLight1" },
    { name: "Settled - Depreciation Outst.", color: "greenLight1" },
    { name: "Settled - Paid", color: "greenBright" },
    { name: "Settled w/ Release", color: "greenLight1" },
    { name: "Settled w/ Release - Paid", color: "greenBright" },
    { name: "Settled w/ Appraisal Award", color: "greenLight1" },
    { name: "Settled w/ Appraisal Award - Depreciation Outst.", color: "greenLight1" },
    { name: "Settled w/ Appraisal Award - Paid", color: "greenBright" },
    { name: "Closed No Service", color: "grayLight1" },
    { name: "Non-Responsive", color: "cyanBright" },
    { name: "Closed - New Claim", color: "blueLight2" },
  ],
  next_steps: [
    { name: "Prepare/Update Claim Summary - CNVR", color: "pinkDark1" },
    { name: "Review Claim Summary", color: "pinkDark1" },
    { name: "Initial Review", color: "cyanBright" },
    { name: "Missing Information", color: "purpleLight1" },
    { name: "Missing Info Requested", color: "greenLight1" },
    { name: "Missing Info Received", color: "yellowLight1" },
    { name: "Assign Firm & Finalize Data", color: "pinkLight1" },
    { name: "Referral Declined", color: "grayLight1" },
    { name: "RP Confirmed: Dead Lead", color: "yellowBright" },
    { name: "Client Declined Representation", color: "redDark1" },
    { name: "RP Client Engagement Needed", color: "pinkLight1" },
    { name: "Prepare Retainer - CNVR", color: "greenBright" },
    { name: "Review Retainer", color: "greenBright" },
    { name: "Retainer Sent - Pending Signature(s)", color: "tealLight1" },
    { name: "Retainer Pending Attorney Signature(s)", color: "greenBright" },
    { name: "Pending Add. Client Signature", color: "purpleBright" },
    { name: "Pending Add. Client Info", color: "blueBright" },
    { name: "Prepare LOR - CNVR", color: "greenBright" },
    { name: "Review LOR", color: "tealLight1" },
    { name: "LOR Sent to IC - Pending Response", color: "pinkLight1" },
    { name: "Prepare Demand Letter - CNVR", color: "yellowBright" },
    { name: "Review Demand Letter", color: "yellowBright" },
    { name: "Demand Letter Pending Approval", color: "yellowBright" },
    { name: "Demand Letter Approved to Send", color: "pinkBright" },
    { name: "Demand Letter Sent to IC - Pending Response", color: "redLight1" },
    { name: "File New Claim", color: "cyanLight1" },
    { name: "Escalation", color: "redLight1" },
    { name: "Warning of suit Email", color: "redLight1" },
    { name: "Active Negotiations", color: "yellowLight2" },
    { name: "Pending BC/Contractor Estimate", color: "blueBright" },
    { name: "Pending BC Inspection Report", color: "tealLight1" },
    { name: "Standing on Denial", color: "cyanLight1" },
    { name: "Pending EUO", color: "orangeBright" },
    { name: "Pending Appraiser Rec. & Consent", color: "pinkLight1" },
    { name: "Pending Appraiser Client Agreement", color: "blueBright" },
    { name: "Prepare Appraisal Demand Letter - CNVR", color: "pinkBright" },
    { name: "Review Appraisal Demand Letter", color: "pinkBright" },
    { name: "Appraisal Demand Pending Approval", color: "pinkBright" },
    { name: "Appraisal Demand Approved", color: "pinkBright" },
    { name: "Pending IC Appraisal Response", color: "cyanBright" },
    { name: "Pending IC Appraisal Response to Escalation", color: "cyanDark1" },
    { name: "Prepare S/C & MTC Appraisal - CNVR", color: "purpleLight1" },
    { name: "Review S/C & MTC Appraisal", color: "purpleLight1" },
    { name: "S/C & MTC Appraisal Pending Approval", color: "blueBright" },
    { name: "S/C & MTC Appraisal Approved to File", color: "blueDark1" },
    { name: "S/C & MTC Appraisal Sent for Service", color: "greenDark1" },
    { name: "Prepare MTC Appraisal - CNVR", color: "purpleLight1" },
    { name: "Review MTC Appraisal", color: "purpleLight1" },
    { name: "MTC Appraisal Pending Approval", color: "purpleLight1" },
    { name: "MTC Appraisal Approved to File", color: "purpleLight1" },
  ],
  category_type: [
    { name: "Cat 1", color: "blueLight2" },
    { name: "Cat 2", color: "cyanLight2" },
    { name: "Cat 3", color: "pinkLight2" },
    { name: "Cat 4", color: "greenLight2" },
  ],
  da_oc: [
    { name: "Desk Adjuster", color: "greenBright" },
    { name: "Opposing Counsel", color: "redBright" },
  ],
  client_rating: [
    { name: "High Maint.", color: "redBright" },
    { name: "Medium Maint.", color: "yellowBright" },
    { name: "Low Maint.", color: "greenBright" },
  ],
  sms_consent: [
    { name: "Opt In", color: "greenLight1" },
    { name: "Opt Out", color: "redBright" },
  ],
  property_type: [
    { name: "Single-Family Residence", color: "greenLight2" },
    { name: "Multi-Family Residence", color: "cyanLight2" },
    { name: "Condominium (Unit Owner)", color: "tealLight2" },
    { name: "Homeowners Association (HOA)", color: "redLight2" },
    { name: "Condominium Owners Association (COA)", color: "pinkLight2" },
    { name: "Commercial", color: "blueLight2" },
    { name: "Industrial", color: "yellowLight2" },
    { name: "Agricultural", color: "orangeLight2" },
    { name: "Other", color: "purpleLight2" },
  ],
  cause_of_loss: [
    { name: "Fire", color: "orangeLight1" },
    { name: "Hail", color: "cyanLight2" },
    { name: "Hurricane", color: "tealLight2" },
    { name: "Lightning", color: "yellowLight1" },
    { name: "Other", color: "orangeLight2" },
    { name: "Plumbing", color: "blueBright" },
    { name: "Theft", color: "redDark1" },
    { name: "Tornado", color: "grayDark1" },
    { name: "Tree Damage", color: "yellowLight1" },
    { name: "Vandalism", color: "pinkLight1" },
    { name: "Water", color: "greenLight2" },
    { name: "Wind", color: "blueLight2" },
    { name: "faulty workmanship", color: "blueLight2" },
  ],
  claim_type: [
    { name: "ACV Policy", color: "cyanLight1" },
    { name: "Emergency Claim", color: "orangeDark1" },
    { name: "Existing Claim", color: "cyanLight2" },
    { name: "New Claim", color: "blueLight2" },
    { name: "Prior Roof Approval", color: "redDark1" },
    { name: "Supplement", color: "blueLight1" },
    { name: "TCS to JPA", color: "blueLight2" },
    { name: "Denied Claim", color: "blueLight2" },
    { name: "HH Option", color: "blueLight2" },
  ],
  total_loss: [
    { name: "Yes", color: "greenLight2" },
    { name: "No", color: "yellowLight1" },
  ],
  contractor: [
    { name: "1st Class Roofing", color: "blueLight2" },
    { name: "5 Star Roofing", color: "orangeLight2" },
    { name: "5D Marketing Guru", color: "cyanBright" },
    { name: "A Roofing Treat", color: "yellowDark1" },
    { name: "A-1 Roofing and Siding", color: "orangeDark1" },
    { name: "A&E Builders", color: "pinkDark1" },
    { name: "Ace Roofing Service", color: "purpleLight2" },
    { name: "Ace Solar and Roofing", color: "tealDark1" },
    { name: "Advanced Roofing Solutions", color: "blueLight2" },
    { name: "All American Restoration & Roofing", color: "orangeDark1" },
    { name: "All Systems Roofing", color: "greenLight2" },
    { name: "Alpha Blue Construction", color: "purpleDark1" },
    { name: "Antwan Milton", color: "purpleLight1" },
    { name: "Armored Roofing LLC", color: "tealLight2" },
    { name: "Arnold Roofing", color: "blueLight2" },
    { name: "ATW Gutter Protection and Roofing", color: "greenLight1" },
    { name: "Austin Justice", color: "greenBright" },
    { name: "B Altman Contractors LLC", color: "yellowDark1" },
    { name: "Benfield Roofing Inc", color: "blueBright" },
    { name: "Best Choice Roofing", color: "redDark1" },
    { name: "Betsill Brothers", color: "cyanBright" },
    { name: "BGC Expert Contractors", color: "blueLight2" },
    { name: "Blue Collar Roofing", color: "blueLight2" },
    { name: "Blue Fox Roofing", color: "tealLight1" },
    { name: "Blue Restoration Services", color: "blueDark1" },
    { name: "Bond Stone Holdings LLC", color: "grayBright" },
    { name: "Boss Roofing and Exteriors", color: "cyanLight2" },
    { name: "Bracken Roofing and Gutter", color: "purpleLight1" },
    { name: "Bradler Built LLC", color: "pinkLight1" },
    { name: "Brazen Roofing", color: "cyanDark1" },
    { name: "Brian Williams", color: "tealLight1" },
    { name: "Browns Roofing", color: "tealLight1" },
    { name: "Butler Roof Company LLC", color: "pinkBright" },
    { name: "Cambra Consulting LLC", color: "blueLight2" },
    { name: "Campbell's Precision Roofing", color: "purpleDark1" },
    { name: "Canopy Roofing", color: "purpleLight2" },
    { name: "Carlos Inguanzo", color: "redLight1" },
    { name: "Carolina Claims Consultants", color: "tealBright" },
    { name: "Carolina Coastal Roofing LLC", color: "blueLight2" },
    { name: "Carolina Performance Roofing", color: "purpleLight2" },
    { name: "Carolina Restoration Pro", color: "redBright" },
    { name: "CAROLINA RESTORATION PRO - CLIVE", color: "orangeDark1" },
    { name: "Carolina Roof Consultants", color: "cyanBright" },
    { name: "Carolina Roofing Experts", color: "redLight2" },
    { name: "Carolina Roofing Pros", color: "yellowLight2" },
    { name: "Carolina Roofing Pros LLC", color: "tealBright" },
    { name: "Carolina Trophy Roofs", color: "greenDark1" },
    { name: "Carolinas Roofing Experts", color: "blueLight2" },
    { name: "CDH Roof & Restoration", color: "greenLight2" },
    { name: "CDS Roofing", color: "redLight1" },
  ],
  insurance_company: [
    { name: "AAA Insurance", color: "grayLight2" },
    { name: "AEGIS", color: "yellowLight2" },
    { name: "Alacrity Solutions/ASI", color: "greenBright" },
    { name: "Alamance Farmers Mutual", color: "blueBright" },
    { name: "Allen Tate", color: "orangeLight1" },
    { name: "Allianz", color: "tealDark1" },
    { name: "Allied Insurance Company of America", color: "blueBright" },
    { name: "Allied Trust", color: "grayBright" },
    { name: "Allstate", color: "blueDark1" },
    { name: "American Bankers Insurance Co of Florida", color: "greenDark1" },
    { name: "American Family Connect", color: "orangeBright" },
    { name: "American Family Home Insurnace", color: "yellowLight1" },
    { name: "American International Group", color: "blueLight1" },
    { name: "American Modern", color: "cyanLight2" },
    { name: "American Mortgage Insurance", color: "blueDark1" },
    { name: "American Western Home Ins", color: "orangeBright" },
    { name: "Ameriprise-Connect Auto-Home", color: "blueLight2" },
    { name: "Amica Mutual", color: "cyanLight1" },
    { name: "Arch Specialist Insurance Company", color: "greenLight2" },
    { name: "Armed Forces Insurance Exchange", color: "blueBright" },
    { name: "Arrowhead", color: "tealLight1" },
    { name: "Associated Industries Insurance Company", color: "cyanLight2" },
    { name: "Assurant", color: "redLight2" },
    { name: "Atain", color: "blueLight2" },
    { name: "Auto Owners", color: "blueLight2" },
    { name: "Auto-Owners Insurance", color: "cyanLight1" },
    { name: "Bakers Claims", color: "greenDark1" },
    { name: "Bankers Insurance Group", color: "purpleLight1" },
    { name: "Berkley Southeast Insurance Group", color: "cyanBright" },
    { name: "Berkshire Hathaway Guard", color: "blueLight2" },
    { name: "Bridgewater", color: "cyanDark1" },
    { name: "Brotherhood Mutual", color: "cyanDark1" },
    { name: "Canopius US Insurance Inc", color: "tealBright" },
    { name: "Carolina Farmers Mutual", color: "yellowBright" },
    { name: "Central Insurance", color: "blueBright" },
    { name: "Certain underwriters at Lloyds", color: "redLight1" },
    { name: "Chubb", color: "redLight2" },
    { name: "Church Insurance Company of Vermont", color: "grayLight1" },
    { name: "Church Mutual", color: "pinkLight2" },
    { name: "Cincinnati", color: "blueLight1" },
    { name: "Citizens", color: "greenLight1" },
    { name: "Colonial Group", color: "cyanLight1" },
    { name: "Commonwealth Insurance", color: "cyanDark1" },
    { name: "Crawford", color: "orangeBright" },
    { name: "Custard Insurance Adjusters", color: "purpleDark1" },
    { name: "Custard Insurance Agency", color: "tealLight1" },
    { name: "DB Insurance", color: "redDark1" },
    { name: "Donegal", color: "grayBright" },
    { name: "Dongbu John Mullen", color: "blueLight2" },
    { name: "Encompass", color: "tealLight2" },
  ],
  current_desk_adjuster: [
    { name: "Aaron Rhoney", color: "cyanDark1" },
    { name: "Alex Dunt", color: "pinkLight1" },
    { name: "Alice Curly", color: "pinkDark1" },
    { name: "Alissa Emad", color: "grayDark1" },
    { name: "Anderson Kirk", color: "greenLight1" },
    { name: "Anne Boyd", color: "yellowBright" },
    { name: "Anthony Gulotta", color: "orangeLight2" },
    { name: "Ashley Davis", color: "tealLight1" },
    { name: "Ashley Gibbon", color: "pinkLight1" },
    { name: "Becky Pebworth", color: "tealDark1" },
    { name: "Belmina", color: "orangeBright" },
    { name: "Billy Burke", color: "cyanLight1" },
    { name: "Billy Saxon", color: "purpleLight2" },
    { name: "Bo Bailey", color: "yellowBright" },
    { name: "Bradley Ottersen", color: "grayLight2" },
    { name: "Brant Hancock", color: "pinkLight2" },
    { name: "Brian Cade", color: "purpleDark1" },
    { name: "Bryan Lawson", color: "tealLight2" },
    { name: "Camden Downs", color: "orangeDark1" },
    { name: "Carla Allen", color: "yellowDark1" },
    { name: "Catherine Shimerling", color: "purpleLight2" },
    { name: "Chance Taylor", color: "purpleBright" },
    { name: "Chaslyn Wilbert", color: "redBright" },
    { name: "Cleston Roberts", color: "redLight1" },
    { name: "Courtney Horne", color: "greenBright" },
    { name: "Craig Honkanen", color: "grayLight2" },
    { name: "Crystal Nuckles", color: "purpleBright" },
    { name: "Dana Rollins", color: "grayLight1" },
    { name: "Dane Busick", color: "redDark1" },
    { name: "Daniel Langdon", color: "orangeLight1" },
    { name: "David C. Hughes", color: "tealDark1" },
    { name: "Denie Perkola", color: "purpleLight2" },
    { name: "Derrick Ball", color: "orangeLight1" },
    { name: "Donald Toomer", color: "redLight2" },
    { name: "Elizabeth Chambers", color: "cyanLight1" },
    { name: "Ericka Woods", color: "purpleLight1" },
    { name: "Evette Grayson", color: "redDark1" },
    { name: "Gabriel Cristian", color: "greenBright" },
    { name: "Gary Heying", color: "greenLight2" },
    { name: "Greg Knox", color: "purpleDark1" },
    { name: "Gregg Beck", color: "redLight1" },
    { name: "Gregory Grimes", color: "greenBright" },
    { name: "Grey Little", color: "greenDark1" },
    { name: "Grey Lyttle", color: "redBright" },
    { name: "Heather Armstrong", color: "redLight2" },
    { name: "Jacob Greenhoe", color: "orangeLight1" },
    { name: "Jailyn Nunez", color: "grayLight2" },
    { name: "James Smith", color: "yellowLight2" },
    { name: "Jasmine Beachem", color: "blueBright" },
    { name: "Jason Campbell", color: "blueBright" },
  ],
  appraisal_type: [
    { name: "FDA", color: "pinkDark1" },
    { name: "CDA", color: "blueBright" },
  ],
  recommended_appraiser: [
    { name: "Alpha Building Consultants-Dave & Dan Schneider", color: "orangeLight1" },
    { name: "Claims-Settlement LLC-Bill Bridges/Caleb Coin", color: "blueLight2" },
    { name: "Claimsmith Group, LLC-Travis K. Smith", color: "purpleBright" },
    { name: "Gold Coast Appraisal-Corey Peacock", color: "yellowLight2" },
    { name: "HD Claims-Brandon Hornick", color: "greenLight1" },
    { name: "Insurance Claim-Stephen Hadhazi", color: "redBright" },
    { name: "Jennifer Pinilla LLC - Jennifer Pinilla", color: "pinkDark1" },
    { name: "Tegui Consulting LLC - Andres Amortegui", color: "blueBright" },
    { name: "Keys Claims Consultants, LLC-George Keys", color: "blueLight1" },
    { name: "Verax Appraisal Services-Josh Otto", color: "tealLight2" },
    { name: "VPA Claims", color: "pinkLight2" },
  ],
  appraiser_next_steps: [
    { name: "File Assigned - Awaiting Appraisal Acceptance (No Action Required)", color: "redBright" },
    { name: "Carrier's Appr. Selected- Schedule Inspection", color: "cyanDark1" },
    { name: "Scheduling Inspection", color: "pinkBright" },
    { name: "Inspection Scheduled", color: "orangeLight2" },
    { name: "Inspection Complete - Pending Estimate", color: "greenBright" },
    { name: "Negotiating Estimates", color: "purpleLight1" },
    { name: "Proceeding with Umpire", color: "yellowLight1" },
    { name: "Agreed Upon Estimate - Pending Award", color: "pinkDark1" },
    { name: "Court Appt. Umpire Needed", color: "tealBright" },
    { name: "Court Appt. Umpire Elected (Firm)", color: "purpleDark1" },
    { name: "Umpire Invoice - Payment Required", color: "orangeBright" },
    { name: "Umpire Invoice - Payment Issued", color: "yellowLight1" },
    { name: "Signed Award - C.P. Submitted to Firm", color: "cyanBright" },
    { name: "Claim Closed & Paid", color: "greenBright" },
    { name: "Appraiser Outcome Concern", color: "redBright" },
  ],
  building_cons_firm_request: [
    { name: "Comparative Estimate", color: "orangeBright" },
    { name: "Field Inspection", color: "blueBright" },
    { name: "Joint Field Inspection", color: "yellowLight1" },
  ],
  building_cons_next_steps: [
    { name: "New Assignment", color: "tealLight1" },
    { name: "Completed Assignment", color: "purpleBright" },
    { name: "Claim Closed & Paid", color: "greenBright" },
  ],
  euo_location: [
    { name: "In Person", color: "blueLight1" },
    { name: "Virtual - Zoom", color: "redLight1" },
  ],
  expert_firm_request: [
    { name: "Required On-Site Inspection", color: "blueBright" },
  ],
  expert_next_steps: [
    { name: "New Assignment", color: "tealLight1" },
    { name: "Completed Assignment", color: "purpleBright" },
    { name: "Claim Closed & Paid", color: "greenBright" },
  ],
  county: [
    { name: "ABBEVILLE COUNTY", color: "yellowLight1" },
    { name: "AIKEN COUNTY", color: "yellowLight2" },
    { name: "ALAMANCE COUNTY", color: "yellowDark1" },
    { name: "ALEXANDER COUNTY", color: "tealLight1" },
    { name: "ALLEGHANY COUNTY", color: "redLight2" },
    { name: "ALLENDALE COUNTY", color: "yellowBright" },
    { name: "ANDERSON COUNTY", color: "orangeLight2" },
    { name: "ANSON COUNTY", color: "blueLight2" },
    { name: "ASHE COUNTY", color: "pinkLight2" },
    { name: "AVERY COUNTY", color: "purpleLight2" },
    { name: "BAMBERG COUNTY", color: "pinkLight2" },
    { name: "BARNWELL COUNTY", color: "redLight2" },
    { name: "BAY COUNTY", color: "orangeLight2" },
    { name: "BEAUFORT COUNTY", color: "pinkLight2" },
    { name: "BERKELEY COUNTY", color: "purpleDark1" },
    { name: "BERTIE COUNTY", color: "greenBright" },
    { name: "BLADEN COUNTY", color: "orangeLight2" },
    { name: "BRUNSWICK COUNTY", color: "pinkLight2" },
    { name: "BUNCOMBE COUNTY", color: "cyanBright" },
    { name: "BURKE COUNTY", color: "pinkBright" },
    { name: "CABARRUS COUNTY", color: "greenLight1" },
    { name: "CALDWELL COUNTY", color: "grayLight2" },
    { name: "CALHOUN COUNTY", color: "grayLight1" },
    { name: "CAMDEN COUNTY", color: "tealDark1" },
    { name: "CARTERET COUNTY", color: "greenLight1" },
    { name: "CASWELL COUNTY", color: "redBright" },
    { name: "CATAWBA COUNTY", color: "greenDark1" },
    { name: "CHARLESTON COUNTY", color: "tealLight2" },
    { name: "CHATHAM COUNTY", color: "orangeDark1" },
    { name: "CHEROKEE COUNTY", color: "grayDark1" },
    { name: "CHESTER COUNTY", color: "cyanLight2" },
    { name: "CHESTERFIELD COUNTY", color: "cyanLight1" },
    { name: "CHOWAN COUNTY", color: "redBright" },
    { name: "CLARENDON COUNTY", color: "grayLight2" },
    { name: "CLAY COUNTY", color: "purpleLight1" },
    { name: "CLEVELAND COUNTY", color: "orangeLight2" },
    { name: "COLLETON COUNTY", color: "pinkBright" },
    { name: "COLUMBUS COUNTY", color: "redLight2" },
    { name: "CRAVEN COUNTY", color: "orangeLight1" },
    { name: "CUMBERLAND COUNTY", color: "orangeBright" },
    { name: "CURRITUCK COUNTY", color: "greenDark1" },
    { name: "DARE COUNTY", color: "grayBright" },
    { name: "DARLINGTON COUNTY", color: "greenLight1" },
    { name: "DAVIDSON COUNTY", color: "yellowLight2" },
    { name: "DAVIE COUNTY", color: "greenLight2" },
    { name: "DILLON COUNTY", color: "cyanLight2" },
    { name: "DORCHESTER COUNTY", color: "yellowDark1" },
    { name: "DOUGLAS COUNTY", color: "orangeDark1" },
    { name: "DUPLIN COUNTY", color: "blueLight1" },
    { name: "DURHAM COUNTY", color: "tealDark1" },
  ],
  deposition_location: [
    { name: "In Person", color: "blueLight1" },
    { name: "Virtual - WebEx", color: "tealLight2" },
    { name: "Virtual - Zoom", color: "redLight1" },
  ],
  motions_location: [
    { name: "In Person", color: "blueLight1" },
    { name: "Virtual - WebEx", color: "tealLight2" },
    { name: "Virtual - Zoom", color: "redLight1" },
  ],
  mediation_location: [
    { name: "In Person", color: "blueLight1" },
    { name: "Virtual - WebEx", color: "tealLight2" },
    { name: "Virtual - Zoom", color: "redLight1" },
  ],
  selected_mediator: [
    { name: "Andrew A. Vanore, III", color: "yellowLight2" },
    { name: "Colleen Byers", color: "purpleLight2" },
    { name: "David Hood", color: "redLight2" },
    { name: "David Wood", color: "blueLight2" },
    { name: "Derek Adler", color: "pinkLight2" },
    { name: "Kevin Elliott", color: "cyanLight2" },
    { name: "Todd Hess", color: "greenLight2" },
    { name: "Tom Williams", color: "orangeLight2" },
    { name: "Walter Burton", color: "tealLight2" },
    { name: "Christopher A. Hicks", color: "yellowLight1" },
    { name: "Patricia B. Todd", color: "grayLight2" },
    { name: "Jesse B. Caldwell", color: "greenBright" },
    { name: "Richard Farley", color: "yellowDark1" },
    { name: "Bill Brazil", color: "grayLight1" },
    { name: "Ronnie Craig", color: "orangeLight1" },
    { name: "Tommy Lydon", color: "yellowBright" },
  ],
  clg_legal_fee: [
    { name: "10%", color: "blueLight1" },
    { name: "20%", color: "cyanLight1" },
    { name: "25%", color: "tealLight1" },
    { name: "30%", color: "greenLight1" },
    { name: "35%", color: "yellowLight1" },
    { name: "40%", color: "orangeLight1" },
  ],
  opposing_counsel_firm: [
    { name: "Bolster Rogers P.C.", color: "orangeDark1" },
    { name: "Brackett & Ellis, P.C.", color: "blueLight2" },
    { name: "Brown Crump & Tierney, PLLC", color: "tealBright" },
    { name: "Butler Snow, LLP", color: "purpleLight2" },
    { name: "Butler Weihmuller Katz Craig, LLC", color: "greenLight2" },
    { name: "Clawson and Staubes, PLLC", color: "yellowBright" },
    { name: "Cranfill Sumner, LLP", color: "yellowLight2" },
    { name: "Goldberg Segalla", color: "yellowLight1" },
    { name: "Haywood, Denny and Miller, L.L.P.", color: "blueBright" },
    { name: "Kevin Elliot Law, PLLC", color: "pinkDark1" },
    { name: "McAngus Goudelock & Courie LLC", color: "pinkLight2" },
    { name: "McAngus Goudelock & Courie, LLC", color: "cyanDark1" },
    { name: "N.C. Grange Mutual Insurance Company", color: "orangeBright" },
    { name: "Nelson Mullins Riley & Scarborough LLP", color: "cyanBright" },
    { name: "O. Craig Tierney", color: "grayBright" },
    { name: "Sweeny Wingate & Barrow, P.A.", color: "greenLight1" },
    { name: "Teague Rotenstreich Stanaland Fox and Holt PLLC", color: "pinkLight1" },
    { name: "The Marion Law Firm, PLLC", color: "redLight2" },
    { name: "Tom Petrus & Miller, LLLC", color: "greenDark1" },
    { name: "Vernis & Bowling of Charlotte, PLLC", color: "greenBright" },
    { name: "Womble Bond Dickinson (US) LLP", color: "grayLight1" },
    { name: "Murphy & Grantland, PA", color: "orangeLight1" },
    { name: "Cam A. Bordman", color: "redDark1" },
    { name: "Hedrick Gardner Kincheloe & Garofalo, LLP", color: "tealDark1" },
    { name: "Robinson Gray Stepp & Laffitte, LLC", color: "purpleLight1" },
  ],
  current_opposing_counsel: [
    { name: "Andrew K. Sonricker", color: "grayDark1" },
    { name: "Christopher J. Blake", color: "cyanLight2" },
    { name: "Daniel Q. Atkinson", color: "greenBright" },
    { name: "Jeffrey S. Bolster", color: "pinkBright" },
    { name: "John T. Jeffries", color: "orangeBright" },
    { name: "Joshua C. Fowler", color: "cyanBright" },
    { name: "Kevin Elliott", color: "redDark1" },
    { name: "Lisa B. Bisso", color: "pinkLight1" },
    { name: "Michael Trask", color: "tealDark1" },
    { name: "N. Denver Smith", color: "yellowBright" },
    { name: "O. Craig Tierney, Jr.", color: "redBright" },
    { name: "R. Gregory Lewis", color: "purpleDark1" },
    { name: "Richard B. Miller", color: "greenDark1" },
    { name: "Robert C. Cratch", color: "tealLight2" },
    { name: "Roger W. Marion, Jr.", color: "redLight1" },
    { name: "Scott Lewis", color: "purpleBright" },
    { name: "Shelley W. Coleman", color: "tealBright" },
    { name: "John R. Kincaid", color: "greenLight1" },
    { name: "Monica Jackson", color: "redLight2" },
    { name: "Jerrod L. Rinehart", color: "purpleLight1" },
    { name: "Stephen M. Kozick", color: "yellowLight1" },
    { name: "Thomas G. Nance", color: "grayLight1" },
    { name: "L. Andrew Watson", color: "purpleLight2" },
    { name: "O. Craig Tierney", color: "blueDark1" },
    { name: "Robert A. Wells", color: "pinkLight2" },
    { name: "Alexander E. Davis", color: "grayBright" },
    { name: "T. Nicholas Goanos", color: "greenLight2" },
    { name: "Josh Fowler", color: "pinkDark1" },
    { name: "J. R. Murphy", color: "orangeDark1" },
    { name: "Sue, Anderson & Bordman, L.L.P.", color: "tealLight1" },
    { name: "William R. Myers", color: "orangeLight2" },
  ],
  rp_appraiser: [
    { name: "Alpha Building Consultants-Dave & Dan Schneider", color: "orangeLight1" },
    { name: "Claims-Settlement LLC-Bill Bridges/Caleb Coin", color: "blueLight2" },
    { name: "Claimsmith Group, LLC-Travis K. Smith", color: "purpleBright" },
    { name: "CLG Appraiser - Test Claim", color: "greenDark1" },
    { name: "Gold Coast Appraisal-Corey Peacock", color: "yellowLight2" },
    { name: "HD Claims-Brandon Hornick", color: "greenLight1" },
    { name: "Insurance Claim-Stephen Hadhazi", color: "redBright" },
    { name: "Jeff Bradley", color: "tealBright" },
    { name: "Josh Otto", color: "blueLight2" },
    { name: "Keys Claims Consultants, LLC-George Keys", color: "blueLight1" },
    { name: "Precision Consulting Inc. - Christian James", color: "cyanLight2" },
    { name: "Verax Appraisal Services-Josh Otto", color: "tealLight2" },
    { name: "VPA Claims", color: "pinkLight2" },
  ],
} as const satisfies Record<string, readonly SelectOption[]>;

export function optionsForDest(key: string): readonly SelectOption[] | null {
  if (key in CASE_SELECT_OPTIONS) {
    return CASE_SELECT_OPTIONS[key as CaseSelectFieldKey];
  }
  return null;
}

export function optionColor(
  key: string,
  name: string,
): AirtableColorToken | null {
  const options = optionsForDest(key);
  if (!options) return null;
  const match = options.find((option) => option.name === name);
  return match?.color ?? null;
}

export function optionStyle(
  key: string,
  name: string,
) {
  const token = optionColor(key, name);
  if (!token) return null;
  return airtablePaletteStyle(token);
}
