-- P11 empty cabinets: cases, contacts, partners, next_steps, files, field_map.
-- Repo copy of the empty schema already applied on conveyordb-testing.
-- Do not apply this file to production. No rows are inserted (including field_map).
-- Attachment / file-slot fields are omitted from cases; PDFs live in files.
-- Formulas are nullable text. Column names and types dumped from the live public schema.

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  case_number text,
  referred_firm text,
  associate_counsel text,
  resolutions_specialist text,
  paralegal text,
  department text,
  case_status text,
  next_steps text[],
  category_type text[],
  da_oc text,
  rs_due_date date,
  pl_due_date date,
  atty_due_date date,
  atty_client_appt timestamptz,
  recent_client_comm_date date,
  next_client_comm_due_date text,
  law_firm_notes text,
  resolutions_notes text,
  attorney_only_notes text,
  accounting_notes text,
  client_profile text,
  associated_cases text,
  property_address text,
  mailing_address text,
  client_alt_phone_number text,
  client_phone_number text,
  email text,
  sms_consent text,
  client_rating text,
  client_name text,
  claim_state text,
  property_type text,
  claim_number text,
  policy_number text,
  date_of_loss date,
  sol_deadline text,
  date_of_breach date,
  dob_deadline text,
  cause_of_loss text[],
  claim_type text[],
  contractor text,
  total_loss text,
  rp_claim_summary_for_litigation text,
  client_estimate_amount numeric,
  current_ic_offer numeric,
  of_est text,
  ic_rcv_estimate_amount numeric,
  rcv_disputed_amount text,
  deductible_amount numeric,
  total_paid_to_date numeric,
  amount_to_collect text,
  certified_policy_received boolean,
  ic_docs_and_communications boolean,
  payment_summary_sol_received boolean,
  nc_call_completed boolean,
  clg_settlement_statement_complete boolean,
  external_documentation_links text,
  insurance_company text,
  opposing_counsel_firm text,
  current_desk_adjuster text,
  current_opposing_counsel text,
  desk_adjuster_email text,
  opposing_counsel_email text,
  ic_adjuster_contact_info text,
  opposing_counsel_contact_info text,
  rp_claim_fee numeric,
  retainer_sent date,
  retainer_signed_date date,
  welcome_email_sent date,
  lor_dl_sent_to_ic date,
  days_since_retained text,
  appraisal_type text,
  recommended_appraiser text,
  appraisal_consent boolean,
  insureds_appraiser text,
  insureds_appraiser_portal_access text,
  carriers_appraiser text,
  rp_appraiser text,
  appraisal_demand_letter_draft text,
  appraisal_demand_sent_to_ic date,
  appraisal_demand_response_due text,
  appraisal_demand_escalation_sent_to_ic date,
  appraisal_demand_escalation_response_due text,
  appraisal_demand_recd_from_ic date,
  firm_appraisal_response_due text,
  appraisal_response_sent_to_ic date,
  appraiser_next_steps text[],
  show_appraisal_milestone_steps boolean,
  notes_for_appraiser text,
  appraiser_response_notes text,
  step_1_initial_appraisal_inspection_scheduled boolean,
  step_1_completed date,
  step_2_site_inspection_completed boolean,
  step_2_completed date,
  step_3_appraisers_estimate_prepared boolean,
  step_3_completed date,
  step_4_appraiser_estimate_exchanged boolean,
  step_4_completed date,
  step_5_joint_scope_review_conducted boolean,
  step_5_completed date,
  step_6_umpire_selected boolean,
  step_6_completed date,
  step_7_umpire_discussions_initiated boolean,
  step_7_completed date,
  step_8_court_appointed_umpire_needed boolean,
  step_8_completed date,
  step_9_evidence_submitted_to_umpire boolean,
  step_9_completed date,
  step_10_umpire_inspection_scheduled boolean,
  step_10_completed date,
  step_11_umpire_site_inspection_completed boolean,
  step_11_completed date,
  step_12_appraisal_award_finalized boolean,
  step_12_completed date,
  step_13_appraisal_award_signed_and_completed boolean,
  step_13_completed date,
  umpire text,
  court_appointed_umpire text,
  u_p_county text,
  u_p_mailed_or_e_filed date,
  u_p_sent_to_abc_legal date,
  u_p_served_date date,
  umpire_hearing_date date,
  appraisal_closing_package_complete boolean,
  notes_for_build_consult_review text,
  build_consult_response_notes text,
  building_consultant text,
  building_consultant_portal_access text,
  building_cons_firm_request text,
  building_cons_next_steps text,
  building_consult_package_complete boolean,
  reinspection_notes text,
  reinspection_scheduled_date timestamptz,
  reinspection_completed boolean,
  euo_date timestamptz,
  euo_location text,
  notes_for_experts_review text,
  expert_response_notes text,
  selected_engineer_experts text,
  engineer_experts_portal_access text,
  expert_firm_request text,
  expert_next_steps text,
  experts_identified_doc text,
  expert_report_complete boolean,
  cat_4_notes text,
  litigation_consent boolean,
  county text,
  s_c_approved boolean,
  s_c_mailed_or_e_filed date,
  s_c_sent_for_service date,
  s_c_served_date date,
  answer_due_date date,
  discovery_to_def_due_date date,
  discovery_from_def_due_date date,
  deposition_date timestamptz,
  deposition_location text,
  deposition_meeting_link text,
  subpoena_docs_due timestamptz,
  motions_hearing_date timestamptz,
  motions_location text,
  mediation_date timestamptz,
  mediation_deadline_date timestamptz,
  mediation_location text,
  selected_mediator text,
  trial_date timestamptz,
  vd_filing_date date,
  refiling_deadline text,
  clg_legal_fee text,
  filing_costs numeric,
  doi_service_costs numeric,
  motion_costs numeric,
  weather_report_costs numeric,
  appraiser_costs numeric,
  building_consultant_costs numeric,
  certified_mailing numeric,
  deposition_costs numeric,
  mediation_costs numeric,
  expert_costs numeric,
  umpire_costs numeric,
  reason_for_disengagement text,
  clg_settlement_statement text,
  settled_date date,
  global_settlement_amount numeric,
  litigation_increase numeric,
  outstanding_funds numeric,
  rp_estimate text,
  release_coc_sent_to_ic date,
  rp_claims_contact text,
  referral_partner text,
  referred_original_case text,
  referred_firm_portal_access text,
  associate_counsel_portal_access text,
  referral_partner_portal_access text,
  conveyor_activity_log text,
  cid_due_date date,
  attorney_repd boolean,
  squares numeric,
  demand_letter_editable text,
  referral_email_recd boolean,
  create_time timestamptz,
  case_documents text,
  referral_case_id text,
  autonum bigint,
  rp_next_steps text[],
  case_id text,
  last_modified timestamptz,
  last_modified_by text,
  invoices text,
  create_invoice boolean,
  emails text,
  case_status_sort text,
  temp_case_docs boolean,
  counsel_legal_name text,
  created_by text,
  mediation_paid boolean,
  experts_paid boolean,
  deposition_paid boolean,
  umpire_paid boolean,
  building_consultant_paid boolean,
  latest_undisp_check_amt numeric,
  settlement_check_amt numeric,
  motions_paid boolean,
  check_1_amount numeric,
  check_1_type text,
  check_1_legal_fee numeric,
  check_2_amount numeric,
  check_2_type text,
  check_2_legal_fee numeric,
  co_counsel_fee_split text,
  check_1_legal_fee_i23za2 text,
  check_1_client_net_disb text,
  check_1_co_counsel_fee text,
  check_1_rs_bonus text,
  check_1_clg_net text,
  check_1_assoc_co_fee text,
  assoc_counsel_fee_split text,
  check_1_deposit_date date,
  check_1_co_counsel_fee_opb5hf numeric,
  check_1_assoc_co_fee_bwlyg3 numeric,
  check_1_rs_bonus_2tida6 numeric,
  rs_bonus text,
  litigation_fees_and_costs text,
  check_1_settl_client_net_disb text,
  check_2_deposit_date date,
  check_2_co_counsel_fee numeric,
  check_2_assoc_co_fee numeric,
  check_2_rs_bonus numeric,
  check_2_legal_fee_szqe6j text,
  check_2_client_net_disb text,
  check_2_co_counsel_fee_hghzxa text,
  check_2_assoc_co_fee_9lifwm text,
  check_2_rs_bonus_admkgy text,
  check_2_clg_net text,
  check_2_settl_client_net_disb text,
  check_3_deposit_date date,
  check_3_type text,
  check_3_amount numeric,
  check_3_legal_fee numeric,
  check_3_co_counsel_fee numeric,
  check_3_assoc_co_fee numeric,
  check_3_rs_bonus numeric,
  check_3_legal_fee_i9ooxd text,
  check_3_client_net_disb text,
  check_3_co_counsel_fee_zfpkb2 text,
  check_3_assoc_co_fee_im7hpx text,
  check_3_rs_bonus_udfjxm text,
  check_3_clg_net text,
  check_3_settl_client_net_disb text,
  check_4_deposit_date date,
  check_4_type text,
  check_4_amount numeric,
  check_4_legal_fee numeric,
  check_4_co_counsel_fee numeric,
  check_4_assoc_co_fee numeric,
  check_4_rs_bonus numeric,
  check_4_legal_fee_ya5yoq text,
  check_4_client_net_disb text,
  check_4_co_counsel_fee_dxoy1o text,
  check_4_assoc_co_fee_fpy85s text,
  check_4_rs_bonus_dnzmsr text,
  check_4_clg_net text,
  check_4_settl_client_net_disb text,
  check_5_deposit_date date,
  check_5_type text,
  check_5_amount numeric,
  check_5_legal_fee numeric,
  check_5_co_counsel_fee numeric,
  check_5_assoc_co_fee numeric,
  check_5_rs_bonus numeric,
  check_5_legal_fee_cqjbxi text,
  check_5_client_net_disb text,
  check_5_co_counsel_fee_aeng4e text,
  check_5_assoc_co_fee_nerzsd text,
  check_5_rs_bonus_ejo79s text,
  rp_fee_split text,
  check_1_rp_fee_split numeric,
  check_2_rp_fee_split numeric,
  check_3_rp_fee_split numeric,
  check_4_rp_fee_split numeric,
  check_5_rp_fee_split numeric,
  check_1_rp_fee_split_nudxhk text,
  check_2_rp_fee_split_rqfdcf text,
  check_3_rp_fee_split_rmedsj text,
  check_4_rp_fee_split_6dd0bl text,
  check_5_rp_fee_split_3o3lpn text,
  check_5_clg_net text,
  check_5_settl_client_net_disb text,
  sum_of_checks_received text,
  insurance_co text,
  dol text,
  claim_no text,
  settlement_statement_sent boolean,
  co_counsel_attorney_and_staff_from_conveyor_users_2 text,
  clg_staff_from_conveyor_users_2 text,
  clg_demo_staff_from_conveyor_users_2 text,
  rs_email text,
  appraisers_from_appraiser_user text,
  building_consultant_from_building_consultant_user text,
  engineer_expert_from_expert_users text,
  referral_partner_from_referral_partner_user text,
  clg_staff_from_building_consult_user text,
  clg_staff_from_referral_partner_user text,
  clg_staff_from_engineer_expert_user text,
  clg_staff_from_appraiser_user text,
  pl_email text,
  co_counsel_email text,
  sol_deadline_notification text,
  co_counsel_email_text text,
  f_60_day_notice_sent boolean,
  f_60_day_notice_date date,
  appraiser_paid boolean,
  pa_fee text,
  check_1_pa_fee numeric,
  check_3_pa_fee numeric,
  check_4_pa_fee numeric,
  check_5_pa_fee numeric,
  check_1_pa_invoice numeric,
  check_2_pa_invoice numeric,
  check_3_pa_invoice numeric,
  check_4_pa_invoice numeric,
  check_5_pa_invoice numeric,
  check_2_pa_fee numeric,
  check_1_pa_fee_percent text,
  check_2_pa_fee_percent text,
  check_3_pa_fee_percent text,
  check_4_pa_fee_percent text,
  check_5_pa_fee_percent text,
  sum_of_legal_fees text,
  sum_of_pa_fee_percent text,
  sum_of_client_net_disb text,
  sum_of_settle_client_net_disb text,
  sum_of_co_counsel_fee text,
  sum_of_assoc_co_fee text,
  sum_of_rs_fee text,
  sum_of_rp_fee_split_fee text,
  sum_of_clg_net text,
  accounting_next_steps text,
  insureds_appraiser_assigned timestamptz,
  appraisal_completed_date_checkbox timestamptz,
  days_pending_w_appraiser text,
  referral_partner_email_lookup text,
  diseng_email_to_rp_sent boolean,
  from_field_associated_client_cases text,
  appraiser_email text,
  clg_demo_staff_from_associate_counsel_portal_access text,
  associate_counsel_from_associate_counsel_portal_access text,
  clg_staff_from_associate_counsel_portal_access text,
  claim_tasks text,
  comments text,
  everson_files text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  full_name text,
  first_name text,
  last_name text,
  relationship_to_insured text,
  policy_party_type text,
  email text,
  primary_phone text,
  secondary_phone_number text,
  preferred_contact_method text,
  best_time_to_contact text,
  authorized_representative_name text,
  authorized_representative_title text,
  qbo_customer_id text,
  associated_cases text,
  contact_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partners (
  id uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  partner_name text,
  status text,
  partner_type text,
  attorney_name text,
  rp_contact_name text,
  license_states text[],
  clg_email text,
  email text,
  office_number text,
  mobile_number text,
  fax_number text,
  physical_address text,
  mailing_address text,
  bar_no text,
  domain text,
  additional_details text,
  rp_fee_percentages text,
  rp_fee_percentages_2026 text,
  counsel_id text,
  of_active_cases text,
  assigned_cases text,
  referred_cases text,
  users text,
  draft_letter_of_representations text,
  draft_retainer_agreements text,
  co_counsel_start_date date,
  managed_cases text,
  draft_retainer_agreement_claimant text,
  draft_retainer_agreement_claimant_and_spouse_or_domestic_p text,
  draft_retainer_agreement_entity text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.next_steps (
  id uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  case_id uuid references public.cases(id) on delete cascade,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  case_id uuid references public.cases(id) on delete cascade,
  slot_name text not null,
  storage_path text,
  content_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.field_map (
  airtable_field_id text primary key,
  cabinet text not null,
  field_name text not null,
  field_type text,
  column_name text,
  skipped text
);

create index if not exists cases_airtable_id_idx on public.cases (airtable_id);
create index if not exists contacts_airtable_id_idx on public.contacts (airtable_id);
create index if not exists partners_airtable_id_idx on public.partners (airtable_id);
create index if not exists next_steps_case_id_idx on public.next_steps (case_id);
create index if not exists files_case_id_idx on public.files (case_id);
create index if not exists files_slot_name_idx on public.files (slot_name);

alter table public.cases enable row level security;
alter table public.contacts enable row level security;
alter table public.partners enable row level security;
alter table public.next_steps enable row level security;
alter table public.files enable row level security;
alter table public.field_map enable row level security;
